document.write(`<p>4) Assinale com um X os nomes de variáveis válidos:</p>`)

alert("a (X) abc")
alert("b ( ) Verdadeiro")
alert("c ( ) 21brasil")
alert("d (X) guarda-chuva")
alert("e ( ) etc.")
alert("f (X) zero")
alert("g (X) guarda_chuva")
alert("h ( ) leia")
alert("i ( ) nome*usuario")
alert("j ( ) #fone")
alert("k ( ) Casa 8")
alert("l (X) endereco")
alert("m ( ) 'cinco'")
alert("n ( ) falso")
alert("o (X) _falso")